[package]
name = "cosmwasm-bignumber"
version = "3.0.0"
authors = ["Terraform Labs, PTE."]
edition = "2018"
description = "Bignumber library for cosmwasm project"
license = "Apache-2.0"
repository = "https://github.com/terra-project/terra-cosmwasm"
homepage = "https://terra.money"
documentation = "https://docs.terra.money"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
#cosmwasm-std = "1.1.5"
cosmwasm-std = "1.0.0"
bigint = "4.4.3"
schemars = "0.8.8"
serde = { version = "1.0.147", default-features = false, features = ["derive"] }

[dev-dependencies]
#cosmwasm-schema = "1.1.5"
cosmwasm-schema = "1.0.0"